#### Importing python request

In [1]:
import requests

#### Importing pandas

In [2]:
import pandas as pd

In [4]:
url = "https://raw.githubusercontent.com/iganabrian/Mock-Data-sate-JSON-file/refs/heads/main/mock.json"

response = requests.get(url)

if response.status_code == 200:
    print('Successfully imported the mock data')
else:
    print('Mock data not found')

Successfully imported the mock data

### Turn the imported data in a DataFrame

In [5]:
data = response.json()

In [6]:
df = pd.DataFrame(data)

df.head(5)

,id,first_name,last_name,email,gender,age,city,country,ip_address
0,1,Garnet,Reynolds-Miller,garnet.reynoldsmiller@company.de,female,40,North Sammiestead,Pitcairn Islands,5.69.6.129
1,2,Waino,Effertz,waino.effertz@outlook.com,female,45,West Judsonview,Faroe Islands,156.162.100.44
2,3,Brody,Hilll,brody.hilll@gmail.com,female,30,Dooleymouth,Mongolia,None
3,4,Alyce,D'Amore,alyce.damore@gmail.com,female,22,West Lafayette,Sint Maarten,None
4,5,Ellis,Paucek,ellis.paucek@gmail.com,female,27,South Alexzanderside,None,66.63.103.165

In [7]:
df.to_csv('Mock Data.csv', index=False)

### Part 3: Working with DummyJSON API Endpoints


Using the Python requests library, extract data from the following DummyJSON endpoints:


Products endpoint
https://dummyjson.com/products


Carts endpoint
https://dummyjson.com/carts

In [13]:
url_products = 'https://dummyjson.com/products'

response = requests.get(url_products)

if response.status_code == 200:
    print ('Product data retrived')
else:
    print('Product data not found')

Product data retrived

### Turn data into a DataFrame

In [14]:
products = response.json()

products_df = pd.DataFrame(products)

products_df.head()

                                            products  total  skip  limit
0  {'id': 1, 'title': 'Essence Mascara Lash Princ...    194     0     30
1  {'id': 2, 'title': 'Eyeshadow Palette with Mir...    194     0     30
2  {'id': 3, 'title': 'Powder Canister', 'descrip...    194     0     30
3  {'id': 4, 'title': 'Red Lipstick', 'descriptio...    194     0     30
4  {'id': 5, 'title': 'Red Nail Polish', 'descrip...    194     0     30

### Export as CSV

In [15]:
products_df.to_csv('Products Dummy Data.csv', index=False)

#### Carts endpoint

In [17]:
url_carts = 'https://dummyjson.com/carts'

response = requests.get(url_products)

if response.status_code == 200:
    print ('Carts data retrived')
else:
    print('Carts data not found')

Carts data retrived

### Turn Carts JSON File to DataFrame

In [18]:
carts = response.json()

carts_df = pd.DataFrame(carts)

carts_df.head()

                                            products  total  skip  limit
0  {'id': 1, 'title': 'Essence Mascara Lash Princ...    194     0     30
1  {'id': 2, 'title': 'Eyeshadow Palette with Mir...    194     0     30
2  {'id': 3, 'title': 'Powder Canister', 'descrip...    194     0     30
3  {'id': 4, 'title': 'Red Lipstick', 'descriptio...    194     0     30
4  {'id': 5, 'title': 'Red Nail Polish', 'descrip...    194     0     30

### Carts DataFrame To csv

In [19]:
products_df.to_csv('Carts Dummy Data.csv', index=False)